package tamagoshi.jeu.actions;

import java.awt.event.ActionEvent;
import java.awt.event.InputEvent;
import java.util.Locale;
import java.util.ResourceBundle;

import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JFrame;
import javax.swing.KeyStroke;

import java.awt.event.KeyEvent;

import tamagoshi.jeu.TamaGameGraphic;
import tamagoshi.jeu.TamaHomeGraphic;
import tamagoshi.language.LanguageAccessor;
import tamagoshi.language.LanguageObserver;
import tamagoshi.properties.TamaConfiguration;

public class ActionPlay extends AbstractAction implements LanguageObserver {
	
	private TamaHomeGraphic home;
	
	public ActionPlay(TamaHomeGraphic home) {
		super();
		this.home=home;
		this.putValue(ACCELERATOR_KEY, KeyStroke.getKeyStroke(KeyEvent.VK_P, InputEvent.CTRL_MASK));
		this.putValue(MNEMONIC_KEY, KeyEvent.VK_P);
		LanguageAccessor languageAcc = LanguageAccessor.getInstance();
		languageAcc.addObservator(this);
	}

	@Override
	public void actionPerformed(ActionEvent arg0) {
		TamaGameGraphic tamaGame;
		if(home.difficultyIsFixed()) {
			tamaGame = new TamaGameGraphic(home.namesAreAutoGenerated(),home.getDifficulty()); 
		}
		else {
			tamaGame = new TamaGameGraphic(home.namesAreAutoGenerated()); 
		}
		TamaGameGraphic tam = new TamaGameGraphic();
		tamaGame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		tamaGame.setSize(500, 250);
		tamaGame.setLocationRelativeTo(null);
		tamaGame.setVisible(true);
		
		TamaConfiguration config = TamaConfiguration.getInstance();
		config.storeProperties();
		
		home.dispose();
		tamaGame.play();
	}
	
	@Override
	public void languageUpdate(LanguageAccessor languageAcc) {
		ResourceBundle languageBundle = languageAcc.getBundle("Home");
		this.putValue(Action.NAME, languageBundle.getString("play"));
	}

}
