package tamagoshi.jeu.actions;

import java.awt.event.ActionEvent;

import javax.swing.AbstractAction;
import javax.swing.JFrame;

import tamagoshi.jeu.TamaGameGraphic;
import tamagoshi.jeu.TamaHomeGraphic;
import tamagoshi.properties.TamaConfiguration;

public class ActionPlay extends AbstractAction {
	
	private TamaHomeGraphic home;
	
	public ActionPlay(String actionName,TamaHomeGraphic home) {
		super(actionName);
		this.home=home;
	}

	@Override
	public void actionPerformed(ActionEvent arg0) {
		TamaGameGraphic tamaGame;
		if(home.difficultyIsFixed()) {
			tamaGame = new TamaGameGraphic(home.namesAreAutoGenerated(),home.getDifficulty()); 
		}
		else {
			tamaGame = new TamaGameGraphic(home.namesAreAutoGenerated()); 
		}
		TamaGameGraphic tam = new TamaGameGraphic();
		tamaGame.setTitle("Jeu des tamagoshis");
		tamaGame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		tamaGame.setSize(500, 250);
		tamaGame.setLocationRelativeTo(null);
		tamaGame.setVisible(true);
		
		TamaConfiguration config = TamaConfiguration.getInstance();
		config.storeProperties();
		
		home.dispose();
		tamaGame.play();
	}

}
